/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 */
plugins {
  kotlin("jvm") version "2.3.20"
  application
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("com.google.guava:guava:33.4.8-jre")
  implementation("com.google.inject:guice:7.0.0")
  implementation("com.github.spullara.mustache.java:compiler:0.9.14")
  implementation("commons-io:commons-io:2.19.0")
  implementation("org.commonmark:commonmark:0.28.0")
  implementation("tools.jackson.dataformat:jackson-dataformat-xml:3.1.0")
  implementation("org.reflections:reflections:0.10.2")
  implementation("org.eclipse.jetty:jetty-server:12.1.7")

  // TODO pick right version for the current platform
  implementation(files("lib/swt-linux-x64.jar"))
}

java.sourceSets["main"].kotlin {
  srcDir("src")
}

java.sourceSets["main"].resources {
  srcDir("resources")
}

application {
  mainClass = "potatoblog.AppKt"
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}
tasks.jar {
  manifest {
    attributes["Main-Class"] = "potatoblog.AppKt"
  }
  configurations["compileClasspath"].forEach { file: File ->
    from(zipTree(file.absoluteFile))
  }
  duplicatesStrategy = DuplicatesStrategy.INCLUDE
}
