/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 */
plugins {
  alias(libs.plugins.kotlin.jvm) 
  application
}

repositories {
  mavenCentral() 

  // for swt
  maven {
    url = uri("https://repository.jboss.org/")
  }
}

dependencies {
  // https://mvnrepository.com/artifact/org.eclipse.swt/org.eclipse.swt
  implementation("org.eclipse.swt:org.eclipse.swt:3.2.0-v3232o")
}

java.sourceSets["main"].kotlin {
  srcDir("src")
}

application {
  mainClass = "potatoblog.AppKt"
}

tasks.named<Test>("test") {
  useJUnitPlatform() 
}
