/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.1/samples
 */
plugins {
  alias(libs.plugins.kotlin.jvm)
  application
}

repositories {
  mavenCentral()
}

dependencies {
  implementation("com.google.guava:guava:33.4.8-jre")
  implementation("com.google.inject:guice:7.0.0")

  // TODO pick right version for the current platform
  implementation(files("lib/swt-linux-x64.jar"))
}

java.sourceSets["main"].kotlin {
  srcDir("src")
}

application {
  mainClass = "potatoblog.AppKt"
}

tasks.named<Test>("test") {
  useJUnitPlatform()
}
tasks.withType<org.gradle.jvm.tasks.Jar>() {
    exclude("META-INF/ECLIPSE_.RSA", "META-INF/ECLIPSE_.SF", "META-INF/MANIFEST.MF")
}
